### ISSUE TITLE
The link of CIFAR-10-C was unvalid

### ISSUE THREAD

**Issue by Awj2021** [taeckyung/SoTTA#2]
Hi, This is a great job! When I downloaded the dataset of CIFAR-10-C, it showed that "HTTP request sent, awaiting response... 403 FORBIDDEN", could you please send the datasets to me by email? Thanks.

**Comment by taeckyung** [comment]
I appreciate your interest. Please visit https://zenodo.org/records/2535967 to download the datasets directly. Sorry for the inconvenience.
