### ISSUE TITLE
Weights for Imagenet and Mnist

### ISSUE THREAD

**Issue by yuanpengtu** [taeckyung/SoTTA#3]
Nice work! And by the way, could you please provide the source pretrained model for Imagenet and Mnist? Thank you!

**Comment by taeckyung** [comment]
Hi,

I appreciate your interest in our work. We provide the pre-trained weights in README.md. FYI, we did not test with MNIST-pretrained models; MNIST is only used to simulate non-interest data.

Best,
Taeckyung
