### ISSUE TITLE
What's evaluation protocol?

### ISSUE THREAD

**Issue by vellichorw** [taeckyung/SoTTA#4]
Hi, author,
Thanks for your code and paper.
I have a few questions about the evaluation protocol. Let's take CIFAR-10-C as an example, for the ''**Near**'' scenario, the online data stream should consists of the original target samples (_i.e._, **Benign**) of CIFAR-10-C and the CIFAR-100 test set (if I understand right). 

- So the model need to classify only the Benign samples or it has to both classify Benign samples and identify samples from CIFAR-100 test set? 

- And accordingly, the dimension of  the classifier is unchanged or the the classifier is expanded to ''C+1''-dim? C for number of categories and 1 for anomaly detection.

Hopefully you can explain more about the new setting. Thx.

**Comment by taeckyung** [comment]
Hi, 

I appreciate your interest in our paper.

We focused on (1) the effect of non-interest samples on test-time adaptation of benign data and (2) methodology to reduce the impact.

Therefore, our test stream consists of non-interest and benign test data without label information. Consequently, it is straightforward to classify all incoming samples, whether benign or not.

Although our methodology aims to reduce the impact of non-interest samples, we do not directly "detect" or "classify" the non-interest samples. We evaluated by only calculating the accuracy of the benign test samples, excluding non-interest samples.

We expect future work to identify and discard non-interest samples in test-time adaptation.

Thank you.
Taeckyung
